galaxy_info:
  author: devroles
  description: >-
    Installs Virtualbox Guest Additions so that a Vagrant box built for
    Virtualbox can already include those accelerators
  license: GPLv3
  min_ansible_version: 2.8
  platforms:
    - name: EL
      versions:
        - all
    - name: Fedora
      versions:
        - all
    - name: Ubuntu
      versions:
        - all

  galaxy_tags:
    - oasis

dependencies: []
