galaxy_info:
  author: devroles
  description: >-
    Install the EPEL repository, but disable it. Shouldn't break on distros
    that don't support EPEL
  license: GPLv3
  min_ansible_version: 2.8
  platforms:
    - name: EL
      versions:
        - all

  galaxy_tags:
    - oasis

dependencies: []
