galaxy_info:
  author: devroles
  description: >-
    Configures older systems that use init instead of systemd for use
    with Vagrant
  license: GPLv3
  min_ansible_version: 2.8
  platforms:
    - name: EL
      versions:
        - 6
    - name: Ubuntu
      versions:
        - all

  galaxy_tags:
    - oasis

dependencies: []
