galaxy_info:
  author: devroles
  description: >-
    Cleans up a new VM before it is ready to be packaged for Vagrant
  license: GPLv3
  min_ansible_version: 2.8
  platforms:
    - name: EL
      versions:
        - 7
    - name: Fedora
      versions:
        - all
    - name: Ubuntu
      versions:
        - all

  galaxy_tags:
    - oasis

dependencies: []
